### ISSUE TITLE
Wrong number of sprites

### ISSUE THREAD

**Issue by mcerdeira** [jamesliu668/Sprite-Sheet-Decomposer#1]
I have a 400x400 image and I choose 80x80, I should get 25 images but I get 25 images (80x80) plus 24 images more 64x64.
I think this is not intentional.

**Comment by Lumiox** [comment]
This was not intentional. I forked this project from its original owner, and added modifications. This problem will be solved. Thank your for your feedback.

Update :
The problem seems to be solved now. I am currently waiting for the owner to accept the pull request.

**Comment by jamesliu668** [comment]
@mcerdeira Please provide your test file so we can test it.

@Lumiox I have merged your updates. Sorry for this late reply.
