### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by imukai** [jamesliu668/Sprite-Sheet-Decomposer#3]
The files seem to lack an alpha channel.  When loaded into Photoshop they have a black background rather than the expected transparency.

**Comment by MattShaile** [comment]
+1

**Comment by peonso** [comment]
+1

**Comment by jamesliu668** [comment]
@imukai @Rustygames @peonso Can anyone provide me a simple file, so I can have a try?

**Comment by peonso** [comment]
@jamesliu668 
First, thanks for this great tool, it's handy.

![sprites](https://user-images.githubusercontent.com/7453795/34393822-a651411c-eb2b-11e7-97c7-b5339fad4262.png)

**Comment by jamesliu668** [comment]
Just tried. The result files have alpha channel. I am opening the file by gimp. Please see the attachments. I search about the "transparent channel in black" on google. This may be the problem and solution:
https://forums.adobe.com/thread/954955

![image](https://user-images.githubusercontent.com/4152618/34397469-4a95f116-ebb1-11e7-9a34-f0cf3f8a564b.png)
![image](https://user-images.githubusercontent.com/4152618/34397454-2e425c5c-ebb1-11e7-9882-f77e2ba29f7f.png)
![image](https://user-images.githubusercontent.com/4152618/34397463-3be61358-ebb1-11e7-913c-975c0a4f187c.png)

**Comment by peonso** [comment]
@jamesliu668, the pixels nearby light of the light pole has transparency and they are fucked up in the second image, you can compare it with the original image.
![untitled-2](https://user-images.githubusercontent.com/7453795/34400194-3da049e4-eb65-11e7-953d-8e40482176f3.png)

**Comment by jamesliu668** [comment]
@peonso I get your point. Some pixels lose their alpha channel data and become black.

**Comment by jamesliu668** [comment]
Fixed.
![1](https://user-images.githubusercontent.com/4152618/34433166-57ebd954-ecb8-11e7-8c5f-64f3bec1c72a.png)
